apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: training

spec:
  type: NodePort
  selector:
    app: testing
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 80
      nodePort: 31000

