version: '3'
services:
   db:
     image: mysql:5.7
     volumes:
       - data:/var/lib/mysql
     networks:
       - network
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: dbuser
       MYSQL_USER: dbuser
       MYSQL_PASSWORD: wordpress
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "9000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: dbuser
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: dbuser
     networks:
       - network

volumes:
    data:

networks:
    network:
